name: release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: build assets for ${{ matrix.os }} with ${{ matrix.cxx }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-linux
          # - os: macos-latest
          #  arch: aarch64-osx
          - os: macos-latest
            arch: x86_64-windows
      # Do not auto-cancel other runners if one fails
      fail-fast: false

    env:
      CXX: ${{ matrix.cxx }}
      TARGET: "adapterremoval3-${{ github.ref_name }}-${{ matrix.arch }}"

    steps:
      - name: Disable man-db building
        if: ${{ matrix.os == 'ubuntu-latest' }}
        # This speeds up apt-get, by preventing the man-db step from running
        run: sudo rm -vf /var/lib/man-db/auto-update

      # - name: harden runner
      #   uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      #   with:
      #     egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # Use mold for faster linking
      # - uses: rui314/setup-mold@45c2b085bbc0283c8e1443d4a511aaa1eda5a3a1 # v1
      #   with:
      #     mold-version: 2.38.0
      #     make-default: true

      - name: dependencies (OS specific)
        run: bash scripts/setup-${{ matrix.os }}.sh

      - if: ${{ matrix.os == 'macos-latest' }}
        name: setup, build, test, and bundle
        run: |
          bash scripts/build-common.sh STATIC=true DOCS=true
          bash scripts/build-bundle.sh "build/install/opt/homebrew" "${TARGET}"

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: setup, build, test, and bundle
        run: |
          make static-container static DOCS=true
          bash scripts/build-bundle.sh "build/static/install/usr/local" "${TARGET}"

      - if: ${{ matrix.os == 'windows-latest' }}
        name: setup, build, test, and bundle
        run: |
          bash scripts/build-common.sh STATIC=true DOCS=true
          bash scripts/build-bundle.sh "build/install/usr/local" "${TARGET}"

      - name: Read changelog
        id: changelog
        shell: bash
        run: |
          r=$(sed '1,/^## /d;/^## /,$d' CHANGES.md)
          r="${r//'%'/'%25'}"    # escape %
          r="${r//$'\n'/'%0A'}"  # escape '\n'
          r="${r//$'\r'/'%0D'}"  # escape '\r'
          echo "TEXT=$r" >> $GITHUB_OUTPUT

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: upload binaries to release
        uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # v2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "adapterremoval3-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz"
          asset_name: "adapterremoval3-${{ github.ref_name }}-${{ matrix.arch }}.tar.gz"
          tag: ${{ github.ref }}
          draft: true
          body: ${{ steps.changelog.outputs.TEXT }}